name = "et3"
main = "./dist/_worker.js"
compatibility_date = "2025-12-03"
compatibility_flags = ["nodejs_compat"]

# Configure the SESSION namespace if session storage is required.
# Replace the placeholder IDs with values from your Cloudflare KV namespace.
[[kv_namespaces]]
binding = "SESSION"
id = "e0daa533410a4867beabfec087ad65fc"
preview_id = "REPLACE_WITH_SESSION_PREVIEW_ID"
